# This is a basic workflow to help you get started with Actions

name: Wireguard 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

          echo Updating
          sudo apt-get update && sudo apt-get upgrade -y

          echo installing deps
          sudo apt install wireguard resolvconf
          
          echo Generating Encryption keys
          wg genkey | sudo tee /etc/wireguard/private.key && chmod go= /etc/wireguard/private.key && cat /etc/wireguard/private.key | wg pubkey | sudo tee

          Enabling port 51820
          sudo apt install ufw && sudo ufw allow ssh && sudo ufw allow 51820/udp 
          sudo ufw enable -y
          sudo ufw status
          
